

url = "https://release.icgms.sharajman.com/"
url_UAT = "https://uat.icgms.insapp.in/"
url_Local = "http://192.168.32.28:4200/"
emailer_url = "https://release-api.icgms.sharajman.com/emailer"
Doc_Link = "C:/Users/parth/OneDrive/Desktop/DTU/Dummy.pdf"
Doc2_Link = "C:/Users/Parth Grover/Desktop/DTU/Dummy.pdf"
Est_Report = "C:/Users/Parth Grover/Desktop/DTU/Sharajman Work/New folder (2)/TestNG Report.pdf"

a1dmin = "superadmnphase1@owleyes.ch" ; P2ass= "Admin123"

Cust_Email10 = "padnunlow@addrin.uk"
Cust_Email2 = "eyebuy741@fanclub.pm"
Cust_Email12 = "testcust1@sendnow.win"
Cust_Email6 = "errox896@exdonuts.com"
Cust_Email4 = "hascap814@tapi.re"
Cust_Email1 = "sumbadlet@eay.jp"
Cust_Email3 = "fatbeg106@cream.pink"
Cust_Email5 = "vandayrid@ruru.be"
Cust_Email11 = "md.jasim@sharajman.com"
Cust_Email7 = "customer11@goatmail.uk"
Cust_Email9 = "pittry583@fuwa.be"
Cust_Email8 = "bartryfry@macr2.com"
Cust_Email13 = "chandini.khan@sharajman.com"
Repairer_Email1 = "repairerphase1@hamham.uk"